version: '3'
services:
  postgres:
    image: postgres
    networks:
      - proxy
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    networks:
      - proxy
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      DIALECT: postgres
      HOST: postgres
      USERNAME_DB: postgres
      PASSWORD_DB: postgres
      DATABASE: postgres
      PORT_DB: 5432
      PORT: 3333

networks:
  proxy:

volumes:
  pgdata: